version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/pontus
    environment:
      BASH_ENV: ~/.bashrc
      AWS_ACCESS_KEY_ID: foobar_key
      AWS_SECRET_ACCESS_KEY: foobar_secret
    docker:
      - image: python:3.4.7
        environment:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apt-get update -qq
            apt-get install -y --no-install-recommends python-dev locales
            echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
            locale-gen
            pip install tox
      - run:
          name: Run Python tests
          when: always
          command: |
            tox
